using System.IO;
using System.Linq;
using Groundsman.Models;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Groundsman.Tests
{
    [TestClass]
    public class GeoJSONObjectTests
    {
        /// <summary>
        /// Try to import a GeoJSONObject
        /// </summary>
        [TestMethod]
        public void ImportGeoJSONObject()
        {
            GeoJSONObject geoJSONObject = GeoJSONObject.ImportGeoJSON(File.ReadAllText("locationsAutoGenerated.json"));
            FeatureCollection featureCollection = (FeatureCollection)geoJSONObject;

            Assert.AreEqual(featureCollection.Features.ToArray().Length, 3);
        }
    }
}
