using Groundsman.Interfaces;
using Groundsman.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Xamarin.Essentials;

namespace Groundsman.Services
{
    public class FeatureStore : IDataStore<Feature>
    {

        public ObservableCollection<Feature> features;

        public FeatureStore()
        {
            features = new ObservableCollection<Feature>();
        }

        public async Task<bool> AddItemAsync(Feature feature)
        {
            bool parseResult = TryParseFeature(feature);
            if (parseResult)
            {
                //EnsureUniqueID(importedFeature);
                features.Add(feature);
                SaveFeaturesToFile(features, AppConstants.FEATURES_FILE);
            }
            return parseResult;
        }

        public async Task<int> AddItemsAsync(FeatureCollection item)
        {
            int successfulImport = 0;
            foreach (Feature feature in item.Features)
            {
                if (TryParseFeature(feature))
                {
                    features.Add(feature);
                    successfulImport++;
                }
            }
            SaveFeaturesToFile(features, AppConstants.FEATURES_FILE);
            return successfulImport;
        }

        public async Task<bool> DeleteItemAsync(Feature item)
        {
            bool deleteSuccessful = features.Remove(item);
            var save = SaveFeaturesToFile(features, AppConstants.FEATURES_FILE);
            return save;
        }

        public async Task<bool> DeleteItemsAsync()
        {
            features.Clear();
            await ImportFeaturesAsync(GetTemplateFile());
            return SaveFeaturesToFile(features, AppConstants.FEATURES_FILE);
        }

        public Task<Feature> GetItemAsync(string id)
        {
            throw new NotImplementedException();
        }

        public async Task<ObservableCollection<Feature>> GetItemsAsync(bool forceRefresh = false)
        {
            if (forceRefresh)
            {
                features.Clear();
                await ImportFeaturesAsync(GetFeaturesFile());
            }
            return features;
        }

        public async Task<bool> UpdateItemAsync(Feature item)
        {
            //bool parseResult = TryParseFeature(item); SHOULD be implemented infuture for final verification once JSON importing is split from general verification
            for (int i = 0; i < features.Count; i++)
            {
                if (features[i].Properties["id"] == item.Properties["id"])
                {
                    features[i] = item;
                }

            }
            return SaveFeaturesToFile(features, AppConstants.FEATURES_FILE);

        }

        private string GetFeaturesFile()
        {
            if (File.Exists(AppConstants.FEATURES_FILE))
            {
                string text = File.ReadAllText(AppConstants.FEATURES_FILE);
                return text;
            }
            else
            {
                return GetTemplateFile();
            }
        }

        private string GetTemplateFile()
        {
            var assembly = IntrospectionExtensions.GetTypeInfo(GetType()).Assembly;
            Stream stream = assembly.GetManifestResourceStream("Groundsman.locationsAutoGenerated.json");
            string text = "";
            using (var reader = new StreamReader(stream))
            {
                text = reader.ReadToEnd();
            }
            return text;
        }

        /// <summary>
        /// Imports GeoJSON and adds the new features to the feature list
        /// </summary>
        /// <param name="importContents">A serialised GeoJSON object</param>
        /// <returns>Number of features successfully imported</returns>
        public async Task<int> ImportFeaturesAsync(string importContents)
        {
            GeoJSONObject importedGeoJSON = GeoJSONObject.ImportGeoJSON(importContents);
            if (importedGeoJSON == null)
            {
                throw new ArgumentException("Import data does not contain valid GeoJSON");
            }
            return importedGeoJSON.Type switch
            {
                GeoJSONType.Point => await AddItemAsync(new Feature((Point)importedGeoJSON)) ? 1 : 0,
                GeoJSONType.LineString => await AddItemAsync(new Feature((LineString)importedGeoJSON)) ? 1 : 0,
                GeoJSONType.Polygon => await AddItemAsync(new Feature((Polygon)importedGeoJSON)) ? 1 : 0,
                GeoJSONType.Feature => await AddItemAsync((Feature)importedGeoJSON) ? 1 : 0,
                GeoJSONType.FeatureCollection => await AddItemsAsync((FeatureCollection)importedGeoJSON),
                _ => throw new ArgumentException("Import data does not contain a supported GeoJSON type."),
            };
        }

        private static bool TryParseFeature(Feature feature)
        {
            if (feature.Properties == null)
            {
                feature.Properties = new Dictionary<string, object>();
            }
            //if feature is freshly created, no need to parse
            if (!feature.Properties.ContainsKey("id"))
            {
                feature.Properties.Add("id", Guid.NewGuid().ToString());
            }
            else if ((string)feature.Properties["id"] == AppConstants.NEW_ENTRY_ID) //Until parsing is properly modular - brand new features are not checked again below
            {
                feature.Properties["id"] = Guid.NewGuid().ToString();
                return true;
            }


            // If author ID hasn't been set on the feature, default it to the user's ID.
            string author = Preferences.Get("UserID", "Groundsman");
            if (feature.Properties.ContainsKey("author"))
            {
                author = (string)feature.Properties["author"];
                if (author.Length > 30)
                {
                    author = author.Substring(0, 30);
                    feature.Properties["author"] = author;
                }
            }
            else
            {
                feature.Properties.Add("author", author);
            }

            // Add default name if empty
            string name = feature.Geometry.Type.ToString();
            if (feature.Properties.ContainsKey("name"))
            {
                name = (string)feature.Properties["name"];
                if (name.Length > 30)
                {
                    name = name.Substring(0, 30);
                    foreach (char c in Path.GetInvalidFileNameChars())
                    {
                        name = name.Replace(c, '-');
                    }
                    feature.Properties["name"] = name;
                }
            }
            else
            {
                feature.Properties.Add("name", name);
            }

            if (feature.Properties.ContainsKey("metadataStringValue"))
            {
                string metadataStringValue = (string)feature.Properties["metadataStringValue"];
                if (!string.IsNullOrEmpty(metadataStringValue) && metadataStringValue.Length > 30)
                {
                    metadataStringValue = name.Substring(0, 30);
                    foreach (char c in Path.GetInvalidFileNameChars())
                    {
                        metadataStringValue = metadataStringValue.Replace(c, '-');
                    }
                    feature.Properties["metadataStringValue"] = metadataStringValue;
                }
            }

            if (feature.Properties.ContainsKey("metadataIntegerValue"))
            {
                try
                {
                    int metadataIntegerValue = Convert.ToInt32(feature.Properties["metadataIntegerValue"]);
                    feature.Properties["metadataIntegerValue"] = metadataIntegerValue;
                }
                catch
                {
                    //Could not parse int value warning
                }
            }

            if (feature.Properties.ContainsKey("metadataFloatValue"))
            {
                try
                {
                    float metadataFloatValue = Convert.ToSingle(feature.Properties["metadataFloatValue"]);
                    feature.Properties["metadataFloatValue"] = metadataFloatValue;
                }
                catch
                {
                    //Could not parse float value warning
                }
            }

            DateTime date = DateTime.Now;
            if (feature.Properties.ContainsKey("date"))
            {
                // If the date field is missing or invalid, convert it into DateTime.Now.
                if (DateTime.TryParse((string)feature.Properties["date"], out date) == false)
                {
                    //warning date couldnt be parsed
                }
                feature.Properties["date"] = date.ToShortDateString();
            }
            else
            {
                feature.Properties.Add("date", date.ToShortDateString());
            }
            return true;
        }

        public bool SaveFeaturesToFile(IList<Feature> features, string FileName)
        {
            FeatureCollection geoJSONObject = new FeatureCollection(features);

            var json = JsonConvert.SerializeObject(geoJSONObject);
            File.WriteAllText(FileName, json);
            return true;
        }

        public async Task<bool> ExportFeatures(IList<Feature> features)
        {
            string fileName = features.Count > 1 ? "Groundsman Feature List" : (string)features[0].Properties["name"];

            SaveFeaturesToFile(features, AppConstants.GetExportFile(fileName));

            await Share.RequestAsync(new ShareFileRequest
            {
                Title = "Features Export",
                File = new ShareFile(AppConstants.GetExportFile(fileName), "text/plain"),
                PresentationSourceBounds = DeviceInfo.Platform == DevicePlatform.iOS && DeviceInfo.Idiom == DeviceIdiom.Tablet
                        ? new System.Drawing.Rectangle((int)(DeviceDisplay.MainDisplayInfo.Width * .474), 80, 0, 0)
                        : System.Drawing.Rectangle.Empty
            });

            return true;
        }
    }
}
