using System.IO;
using System.Reflection;
using Groundsman.Models;
using Xamarin.Essentials;

namespace Groundsman
{
    public static class Constants
    {
        // Files paths and names
        private static readonly string DATA_PATH = FileSystem.AppDataDirectory;
        private static readonly string CACHE_PATH = FileSystem.CacheDirectory;

        private static readonly string FEATURES_FILENAME = "locations.json";
        private static readonly string DELETED_FEATURE_FILENAME = "deleted.json";
        private static readonly string EXPORT_LOG_FILENAME = "Groundsman Log.csv";

        public static readonly string FEATURES_FILE = Path.Combine(DATA_PATH, FEATURES_FILENAME);
        public static readonly string DELETED_FEATURE_FILE = Path.Combine(CACHE_PATH, DELETED_FEATURE_FILENAME);
        public static readonly string EXPORT_LOG_FILE = Path.Combine(CACHE_PATH, EXPORT_LOG_FILENAME);


        // Preference keys
        public static readonly string UserIDKey = "UserID";
        public static readonly string GPSPrecisionKey = "GPSPrecision";
        public static readonly string DecimalAccuracyKey = "DecimalAccuracy";
        public static readonly string ShakeToUndoKey = "EnableShakeToUndo";
        public static readonly string MapDrawPointsKey = "ShowPointsOnMap";
        public static readonly string MapDrawLinesKey = "ShowLinesOnMap";
        public static readonly string MapDrawPolygonsKey = "ShowPolygonsOnMap";
        public static readonly string ShareLogAsGeoJSONKey = "ShareLogAsGeoJSONKey";


        // Hardcoded feature property keys
        public static readonly string IdentifierProperty = "id";
        public static readonly string NameProperty = "name";
        public static readonly string DateProperty = "date";
        public static readonly string AuthorProperty = "author";
        public static readonly string LogDateTimeListProperty = "DateTimes";

        // Feature property values
        public static readonly string NewFeatureID = "-1";
        public static readonly string DefaultUserValue = "Groundsman";
        public static readonly int DefaultGPSPrecisionValue = 2;
        public static readonly int DefaultDecimalAccuracyValue = 6;

        /// <summary>
        /// Fetches the local features list file if it exists, otherwise the default feature list
        /// </summary>
        /// <returns>Contents of file (serialised GeoJSON)</returns>
        public static string FeaturesFileContents => File.Exists(FEATURES_FILE) ? File.ReadAllText(FEATURES_FILE) : GetTemplateFile();

        /// <summary>
        /// Gets the default features list
        /// </summary>
        /// <returns>Serialised GeoJSON contents of the default features list</returns>
        public static string GetTemplateFile()
        {
            Assembly assembly = IntrospectionExtensions.GetTypeInfo(Xamarin.Forms.Application.Current.GetType()).Assembly;
            Stream stream = assembly.GetManifestResourceStream("Groundsman.locationsAutoGenerated.json");
            using StreamReader reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }

        /// <summary>
        /// Gives the correct export file name and extension
        /// </summary>
        /// <param name="fileName">Name of the export file</param>
        /// <param name="type">the filetype to export to</param>
        /// <returns>Full export file path string</returns>
        public static string GetExportFile(string fileName, ExportType type) => type switch
        {
            ExportType.GeoJSON => Path.Combine(CACHE_PATH, fileName + ".json"),
            ExportType.CSV => Path.Combine(CACHE_PATH, fileName + ".csv"),
            _ => Path.Combine(CACHE_PATH, fileName),
        };
    }
}